### ISSUE TITLE
Not Install sysctl error

### ISSUE THREAD

**Issue by THAVASIGTI** [william-gr/py-sysctl#15]
machine : Ubuntu (18.04)

ERROR : 

Defaulting to user installation because normal site-packages is not writeable
Collecting sysctl
  Downloading sysctl-0.2.tar.gz (7.2 kB)
Building wheels for collected packages: sysctl
  Building wheel for sysctl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nv1bnq0a
       cwd: /tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/
  Complete output (110 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/sysctl
  copying sysctl/__init__.py -> build/lib.linux-x86_64-3.6/sysctl
  creating build/lib.linux-x86_64-3.6/sysctl/tests
  copying sysctl/tests/test_sysctl_w.py -> build/lib.linux-x86_64-3.6/sysctl/tests
  copying sysctl/tests/test_sysctl_setvalue.py -> build/lib.linux-x86_64-3.6/sysctl/tests
  copying sysctl/tests/__init__.py -> build/lib.linux-x86_64-3.6/sysctl/tests
  copying sysctl/tests/test_sysctl_a_num.py -> build/lib.linux-x86_64-3.6/sysctl/tests
  running build_ext
  building 'sysctl/_sysctl' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/sysctl
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c sysctl/_sysctl.c -o build/temp.linux-x86_64-3.6/sysctl/_sysctl.o -Wall
  sysctl/_sysctl.c:37:21: error: ‘CTLTYPE’ undeclared here (not in a function); did you mean ‘CTL_PM’?
   static int ctl_size[CTLTYPE+1] = {
                       ^~~~~~~
                       CTL_PM
  sysctl/_sysctl.c:38:3: error: ‘CTLTYPE_INT’ undeclared here (not in a function); did you mean ‘CTLTYPE’?
    [CTLTYPE_INT] = sizeof(int),
     ^~~~~~~~~~~
     CTLTYPE
  sysctl/_sysctl.c:38:3: error: array index in initializer not of integer type
  sysctl/_sysctl.c:38:3: note: (near initialization for ‘ctl_size’)
  sysctl/_sysctl.c:39:3: error: ‘CTLTYPE_UINT’ undeclared here (not in a function); did you mean ‘CTLTYPE_INT’?
    [CTLTYPE_UINT] = sizeof(u_int),
     ^~~~~~~~~~~~
     CTLTYPE_INT
  sysctl/_sysctl.c:39:3: error: array index in initializer not of integer type
  sysctl/_sysctl.c:39:3: note: (near initialization for ‘ctl_size’)
  sysctl/_sysctl.c:40:3: error: ‘CTLTYPE_LONG’ undeclared here (not in a function); did you mean ‘CTLTYPE_UINT’?
    [CTLTYPE_LONG] = sizeof(long),
     ^~~~~~~~~~~~
     CTLTYPE_UINT
  sysctl/_sysctl.c:40:3: error: array index in initializer not of integer type
  sysctl/_sysctl.c:40:3: note: (near initialization for ‘ctl_size’)
  sysctl/_sysctl.c:41:3: error: ‘CTLTYPE_ULONG’ undeclared here (not in a function); did you mean ‘CTLTYPE_LONG’?
    [CTLTYPE_ULONG] = sizeof(u_long),
     ^~~~~~~~~~~~~
     CTLTYPE_LONG
  sysctl/_sysctl.c:41:3: error: array index in initializer not of integer type
  sysctl/_sysctl.c:41:3: note: (near initialization for ‘ctl_size’)
  sysctl/_sysctl.c:46:3: error: ‘CTLTYPE_QUAD’ undeclared here (not in a function); did you mean ‘CTLTYPE_LONG’?
    [CTLTYPE_QUAD] = sizeof(int64_t),
     ^~~~~~~~~~~~
     CTLTYPE_LONG
  sysctl/_sysctl.c:46:3: error: array index in initializer not of integer type
  sysctl/_sysctl.c:46:3: note: (near initialization for ‘ctl_size’)
  sysctl/_sysctl.c: In function ‘Sysctl_setvalue’:
  sysctl/_sysctl.c:138:26: error: ‘PyInt_Type’ undeclared (first use in this function); did you mean ‘PySet_Type’?
      if(value->ob_type != &PyInt_Type) {
                            ^~~~~~~~~~
                            PySet_Type
  sysctl/_sysctl.c:138:26: note: each undeclared identifier is reported only once for each function it appears in
  sysctl/_sysctl.c: In function ‘new_sysctlobj’:
  sysctl/_sysctl.c:343:8: error: ‘CTLTYPE_STRING’ undeclared (first use in this function); did you mean ‘CTLTYPE_ULONG’?
     case CTLTYPE_STRING:
          ^~~~~~~~~~~~~~
          CTLTYPE_ULONG
  sysctl/_sysctl.c:438:8: error: ‘CTLTYPE_OPAQUE’ undeclared (first use in this function); did you mean ‘CTLTYPE_QUAD’?
     case CTLTYPE_OPAQUE:
          ^~~~~~~~~~~~~~
          CTLTYPE_QUAD
  sysctl/_sysctl.c:445:12: warning: implicit declaration of function ‘PyInt_FromLong’; did you mean ‘PyLong_FromLong’? [-Wimplicit-function-declaration]
       item = PyInt_FromLong(ci->hz);
              ^~~~~~~~~~~~~~
              PyLong_FromLong
  sysctl/_sysctl.c:445:29: error: dereferencing pointer to incomplete type ‘struct clockinfo’
       item = PyInt_FromLong(ci->hz);
                               ^~
  sysctl/_sysctl.c:473:36: error: ‘CTLFLAG_WR’ undeclared (first use in this function)
    writable = PyBool_FromLong(kind & CTLFLAG_WR);
                                      ^~~~~~~~~~
  sysctl/_sysctl.c:474:36: error: ‘CTLFLAG_TUN’ undeclared (first use in this function); did you mean ‘CTLFLAG_WR’?
    tuneable = PyBool_FromLong(kind & CTLFLAG_TUN);
                                      ^~~~~~~~~~~
                                      CTLFLAG_WR
  sysctl/_sysctl.c: In function ‘sysctl_filter’:
  sysctl/_sysctl.c:521:18: error: ‘CTLTYPE_NODE’ undeclared (first use in this function); did you mean ‘CTLTYPE_LONG’?
      if(ctltype == CTLTYPE_NODE) {
                    ^~~~~~~~~~~~
                    CTLTYPE_LONG
  sysctl/_sysctl.c:556:50: error: ‘CTLFLAG_WR’ undeclared (first use in this function)
     if( (PyObject *)writable == Py_True && (kind & CTLFLAG_WR) == 0 ) {
                                                    ^~~~~~~~~~
  sysctl/_sysctl.c: In function ‘PyInit__sysctl’:
  sysctl/_sysctl.c:648:45: error: ‘CTLTYPE_NODE’ undeclared (first use in this function); did you mean ‘CTLTYPE_LONG’?
    PyModule_AddIntConstant(m, "CTLTYPE_NODE", CTLTYPE_NODE);
                                               ^~~~~~~~~~~~
                                               CTLTYPE_LONG
  sysctl/_sysctl.c:650:47: error: ‘CTLTYPE_STRING’ undeclared (first use in this function); did you mean ‘CTLTYPE_ULONG’?
    PyModule_AddIntConstant(m, "CTLTYPE_STRING", CTLTYPE_STRING);
                                                 ^~~~~~~~~~~~~~
                                                 CTLTYPE_ULONG
  sysctl/_sysctl.c:651:47: error: ‘CTLTYPE_OPAQUE’ undeclared (first use in this function); did you mean ‘CTLTYPE_NODE’?
    PyModule_AddIntConstant(m, "CTLTYPE_OPAQUE", CTLTYPE_OPAQUE);
                                                 ^~~~~~~~~~~~~~
                                                 CTLTYPE_NODE
  sysctl/_sysctl.c:652:47: error: ‘CTLTYPE_STRUCT’ undeclared (first use in this function); did you mean ‘CTLTYPE_STRING’?
    PyModule_AddIntConstant(m, "CTLTYPE_STRUCT", CTLTYPE_STRUCT);
                                                 ^~~~~~~~~~~~~~
                                                 CTLTYPE_STRING
  At top level:
  sysctl/_sysctl.c:37:12: warning: ‘ctl_size’ defined but not used [-Wunused-variable]
   static int ctl_size[CTLTYPE+1] = {
              ^~~~~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for sysctl
  Running setup.py clean for sysctl
Failed to build sysctl
Installing collected packages: sysctl
    Running setup.py install for sysctl ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s_3zcrn_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/gti/.local/include/python3.6m/sysctl
         cwd: /tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/
    Complete output (110 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/sysctl
    copying sysctl/__init__.py -> build/lib.linux-x86_64-3.6/sysctl
    creating build/lib.linux-x86_64-3.6/sysctl/tests
    copying sysctl/tests/test_sysctl_w.py -> build/lib.linux-x86_64-3.6/sysctl/tests
    copying sysctl/tests/test_sysctl_setvalue.py -> build/lib.linux-x86_64-3.6/sysctl/tests
    copying sysctl/tests/__init__.py -> build/lib.linux-x86_64-3.6/sysctl/tests
    copying sysctl/tests/test_sysctl_a_num.py -> build/lib.linux-x86_64-3.6/sysctl/tests
    running build_ext
    building 'sysctl/_sysctl' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/sysctl
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c sysctl/_sysctl.c -o build/temp.linux-x86_64-3.6/sysctl/_sysctl.o -Wall
    sysctl/_sysctl.c:37:21: error: ‘CTLTYPE’ undeclared here (not in a function); did you mean ‘CTL_PM’?
     static int ctl_size[CTLTYPE+1] = {
                         ^~~~~~~
                         CTL_PM
    sysctl/_sysctl.c:38:3: error: ‘CTLTYPE_INT’ undeclared here (not in a function); did you mean ‘CTLTYPE’?
      [CTLTYPE_INT] = sizeof(int),
       ^~~~~~~~~~~
       CTLTYPE
    sysctl/_sysctl.c:38:3: error: array index in initializer not of integer type
    sysctl/_sysctl.c:38:3: note: (near initialization for ‘ctl_size’)
    sysctl/_sysctl.c:39:3: error: ‘CTLTYPE_UINT’ undeclared here (not in a function); did you mean ‘CTLTYPE_INT’?
      [CTLTYPE_UINT] = sizeof(u_int),
       ^~~~~~~~~~~~
       CTLTYPE_INT
    sysctl/_sysctl.c:39:3: error: array index in initializer not of integer type
    sysctl/_sysctl.c:39:3: note: (near initialization for ‘ctl_size’)
    sysctl/_sysctl.c:40:3: error: ‘CTLTYPE_LONG’ undeclared here (not in a function); did you mean ‘CTLTYPE_UINT’?
      [CTLTYPE_LONG] = sizeof(long),
       ^~~~~~~~~~~~
       CTLTYPE_UINT
    sysctl/_sysctl.c:40:3: error: array index in initializer not of integer type
    sysctl/_sysctl.c:40:3: note: (near initialization for ‘ctl_size’)
    sysctl/_sysctl.c:41:3: error: ‘CTLTYPE_ULONG’ undeclared here (not in a function); did you mean ‘CTLTYPE_LONG’?
      [CTLTYPE_ULONG] = sizeof(u_long),
       ^~~~~~~~~~~~~
       CTLTYPE_LONG
    sysctl/_sysctl.c:41:3: error: array index in initializer not of integer type
    sysctl/_sysctl.c:41:3: note: (near initialization for ‘ctl_size’)
    sysctl/_sysctl.c:46:3: error: ‘CTLTYPE_QUAD’ undeclared here (not in a function); did you mean ‘CTLTYPE_LONG’?
      [CTLTYPE_QUAD] = sizeof(int64_t),
       ^~~~~~~~~~~~
       CTLTYPE_LONG
    sysctl/_sysctl.c:46:3: error: array index in initializer not of integer type
    sysctl/_sysctl.c:46:3: note: (near initialization for ‘ctl_size’)
    sysctl/_sysctl.c: In function ‘Sysctl_setvalue’:
    sysctl/_sysctl.c:138:26: error: ‘PyInt_Type’ undeclared (first use in this function); did you mean ‘PySet_Type’?
        if(value->ob_type != &PyInt_Type) {
                              ^~~~~~~~~~
                              PySet_Type
    sysctl/_sysctl.c:138:26: note: each undeclared identifier is reported only once for each function it appears in
    sysctl/_sysctl.c: In function ‘new_sysctlobj’:
    sysctl/_sysctl.c:343:8: error: ‘CTLTYPE_STRING’ undeclared (first use in this function); did you mean ‘CTLTYPE_ULONG’?
       case CTLTYPE_STRING:
            ^~~~~~~~~~~~~~
            CTLTYPE_ULONG
    sysctl/_sysctl.c:438:8: error: ‘CTLTYPE_OPAQUE’ undeclared (first use in this function); did you mean ‘CTLTYPE_QUAD’?
       case CTLTYPE_OPAQUE:
            ^~~~~~~~~~~~~~
            CTLTYPE_QUAD
    sysctl/_sysctl.c:445:12: warning: implicit declaration of function ‘PyInt_FromLong’; did you mean ‘PyLong_FromLong’? [-Wimplicit-function-declaration]
         item = PyInt_FromLong(ci->hz);
                ^~~~~~~~~~~~~~
                PyLong_FromLong
    sysctl/_sysctl.c:445:29: error: dereferencing pointer to incomplete type ‘struct clockinfo’
         item = PyInt_FromLong(ci->hz);
                                 ^~
    sysctl/_sysctl.c:473:36: error: ‘CTLFLAG_WR’ undeclared (first use in this function)
      writable = PyBool_FromLong(kind & CTLFLAG_WR);
                                        ^~~~~~~~~~
    sysctl/_sysctl.c:474:36: error: ‘CTLFLAG_TUN’ undeclared (first use in this function); did you mean ‘CTLFLAG_WR’?
      tuneable = PyBool_FromLong(kind & CTLFLAG_TUN);
                                        ^~~~~~~~~~~
                                        CTLFLAG_WR
    sysctl/_sysctl.c: In function ‘sysctl_filter’:
    sysctl/_sysctl.c:521:18: error: ‘CTLTYPE_NODE’ undeclared (first use in this function); did you mean ‘CTLTYPE_LONG’?
        if(ctltype == CTLTYPE_NODE) {
                      ^~~~~~~~~~~~
                      CTLTYPE_LONG
    sysctl/_sysctl.c:556:50: error: ‘CTLFLAG_WR’ undeclared (first use in this function)
       if( (PyObject *)writable == Py_True && (kind & CTLFLAG_WR) == 0 ) {
                                                      ^~~~~~~~~~
    sysctl/_sysctl.c: In function ‘PyInit__sysctl’:
    sysctl/_sysctl.c:648:45: error: ‘CTLTYPE_NODE’ undeclared (first use in this function); did you mean ‘CTLTYPE_LONG’?
      PyModule_AddIntConstant(m, "CTLTYPE_NODE", CTLTYPE_NODE);
                                                 ^~~~~~~~~~~~
                                                 CTLTYPE_LONG
    sysctl/_sysctl.c:650:47: error: ‘CTLTYPE_STRING’ undeclared (first use in this function); did you mean ‘CTLTYPE_ULONG’?
      PyModule_AddIntConstant(m, "CTLTYPE_STRING", CTLTYPE_STRING);
                                                   ^~~~~~~~~~~~~~
                                                   CTLTYPE_ULONG
    sysctl/_sysctl.c:651:47: error: ‘CTLTYPE_OPAQUE’ undeclared (first use in this function); did you mean ‘CTLTYPE_NODE’?
      PyModule_AddIntConstant(m, "CTLTYPE_OPAQUE", CTLTYPE_OPAQUE);
                                                   ^~~~~~~~~~~~~~
                                                   CTLTYPE_NODE
    sysctl/_sysctl.c:652:47: error: ‘CTLTYPE_STRUCT’ undeclared (first use in this function); did you mean ‘CTLTYPE_STRING’?
      PyModule_AddIntConstant(m, "CTLTYPE_STRUCT", CTLTYPE_STRUCT);
                                                   ^~~~~~~~~~~~~~
                                                   CTLTYPE_STRING
    At top level:
    sysctl/_sysctl.c:37:12: warning: ‘ctl_size’ defined but not used [-Wunused-variable]
     static int ctl_size[CTLTYPE+1] = {
                ^~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ed_bzq80/sysctl_a22ad63c27864db090680ac5a41d1099/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s_3zcrn_/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/gti/.local/include/python3.6m/sysctl Check the logs for full command output.

**Comment by william-gr** [comment]
Only works on FreeSBD

**Comment by THAVASIGTI** [comment]
Okay , thank you for reply
